t    |   897 passing (5h)
hardhat    |   14 failing
hardhat    | 
hardhat    |   1) AladdinConvexVault.add.14883496.spec
hardhat    |        pusd pool
hardhat    |          deposit
hardhat    |            should succeed, when deposit with ETH:
hardhat    | 
hardhat    |       AssertionError: Expected "189400005231356784320518" to be equal 188769665166339566851749
hardhat    |       + expected - actual
hardhat    | 
hardhat    |        {
hardhat    |       -  "_hex": "0x27f9395b943c4b51d6a5"
hardhat    |       +  "_hex": "0x281b651559af1332a006"
hardhat    |          "_isBigNumber": true
hardhat    |        }
hardhat    |       
hardhat    |       at Context.<anonymous> (test/concentrator/AladdinConvexVault.add.14883496.spec.ts:202:27)
hardhat    | 
hardhat    |   2) AladdinConvexVault.add.14883496.spec
hardhat    |        pusd pool
hardhat    |          deposit
hardhat    |            should succeed, when deposit with WETH:
hardhat    | 
hardhat    |       AssertionError: Expected "189400005231356784320518" to be equal 188769665166339566851749
hardhat    |       + expected - actual
hardhat    | 
hardhat    |        {
hardhat    |       -  "_hex": "0x27f9395b943c4b51d6a5"
hardhat    |       +  "_hex": "0x281b651559af1332a006"
hardhat    |          "_isBigNumber": true
hardhat    |        }
hardhat    |       
hardhat    |       at Context.<anonymous> (test/concentrator/AladdinConvexVault.add.14883496.spec.ts:222:27)
hardhat    | 
hardhat    |   3) AladdinConvexVault.add.14883496.spec
hardhat    |        pusd pool
hardhat    |          withdraw
hardhat    |            should succeed, when harvest:
hardhat    |      Error: call revert exception; VM Exception while processing transaction: reverted with reason string "!>0" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="harvest(uint256,address,uint256)", data="0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003213e300000000000000000000000000000000000000000000000000000000000", errorArgs=["!>0"], errorName="Error", errorSignature="Error(string)", reason="!>0", code=CALL_EXCEPTION, version=abi/5.6.4)
hardhat    |       at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
hardhat    |       at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
hardhat    |       at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
hardhat    |       at Object.<anonymous> (node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
hardhat    |       at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
hardhat    |       at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
hardhat    |       at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:20:58)
hardhat    | 
hardhat    |   4) ConcentratorIFOVault.deploy.spec
hardhat    |        ifo for pool: tricrypto2
hardhat    |          "before each" hook for "deposit, withdraw as USDC, deposit from USDC":
hardhat    |      Error: Timeout of 400000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/usr/app/test/concentrator/ConcentratorIFOVault.deploy.spec.ts)
hardhat    |       at runMicrotasks (<anonymous>)
hardhat    |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hardhat    |       at runNextTicks (node:internal/process/task_queues:65:3)
hardhat    |       at listOnTimeout (node:internal/timers:528:9)
hardhat    |       at processTimers (node:internal/timers:502:7)
hardhat    | 
hardhat    |   5) ConcentratorIFOVault.deploy.spec
hardhat    |        ifo for pool: sbtc
hardhat    |          harvest
hardhat    |            should succeed:
hardhat    |      Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="harvest(uint256,address,uint256)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
hardhat    |       at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
hardhat    |       at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
hardhat    |       at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
hardhat    |       at Object.<anonymous> (node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
hardhat    |       at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
hardhat    |       at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
hardhat    |       at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:20:58)
hardhat    | 
hardhat    |   6) ConcentratorIFOVault.deploy.spec
hardhat    |        ifo for pool: seth
hardhat    |          harvest
hardhat    |            should succeed:
hardhat    |      Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="harvest(uint256,address,uint256)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
hardhat    |       at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
hardhat    |       at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
hardhat    |       at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
hardhat    |       at Object.<anonymous> (node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
hardhat    |       at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
hardhat    |       at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
hardhat    |       at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:20:58)
hardhat    | 
hardhat    |   7) BalancerLPGaugeGateway.spec
hardhat    |        should succeed, when zap from [CVXCRV]:
hardhat    |      Error: invalid contract address or ENS name (argument="addressOrName", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.6.2)
hardhat    |       at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
hardhat    |       at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
hardhat    |       at Logger.throwArgumentError (node_modules/@ethersproject/logger/src.ts/index.ts:277:21)
hardhat    |       at Contract.BaseContract (node_modules/@ethersproject/contracts/src.ts/index.ts:712:20)
hardhat    |       at new Contract (node_modules/@ethersproject/contracts/lib/index.js:1053:42)
hardhat    |       at Function.ContractFactory.getContract (node_modules/@ethersproject/contracts/src.ts/index.ts:1297:16)
hardhat    |       at ContractFactory.attach (node_modules/@ethersproject/contracts/src.ts/index.ts:1260:42)
hardhat    |       at getContractAtFromArtifact (node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:352:26)
hardhat    | 
hardhat    |   8) AladdinZap.spec
hardhat    |        UniswapV2 FXS/FRAX pool [UniswapV2]
hardhat    |          should succeed, when swap FRAX => FXS:
hardhat    |      HeadersTimeoutError: Headers Timeout Error
hardhat    |       at Timeout.onParserTimeout [as _onTimeout] (node_modules/undici/lib/client.js:893:26)
hardhat    |       at listOnTimeout (node:internal/timers:561:11)
hardhat    |       at processTimers (node:internal/timers:502:7)
hardhat    | 
hardhat    |   9) AladdinZap.spec
hardhat    |        UniswapV3 FXS/ETH pool [UniswapV3]
hardhat    |          should succeed, when swap ETH => FXS:
hardhat    |      Error: Timeout of 400000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/usr/app/test/zap/AladdinZap.spec.ts)
hardhat    |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hardhat    |       at runNextTicks (node:internal/process/task_queues:65:3)
hardhat    |       at listOnTimeout (node:internal/timers:528:9)
hardhat    |       at processTimers (node:internal/timers:502:7)
hardhat    | 
hardhat    |   10) AladdinZap.spec
hardhat    |        curve steth pool [CurveETHPool]
hardhat    |          should succeed, when AddLiquidity ETH => steCRV:
hardhat    |      Error: Timeout of 400000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/usr/app/test/zap/AladdinZap.spec.ts)
hardhat    |       at runMicrotasks (<anonymous>)
hardhat    |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hardhat    |       at runNextTicks (node:internal/process/task_queues:65:3)
hardhat    |       at listOnTimeout (node:internal/timers:528:9)
hardhat    |       at processTimers (node:internal/timers:502:7)
hardhat    | 
hardhat    |   11) AladdinZap.spec
hardhat    |        curve steth pool [CurveETHPool]
hardhat    |          should succeed, when Swap ETH => stETH:
hardhat    |      Error: Timeout of 400000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/usr/app/test/zap/AladdinZap.spec.ts)
hardhat    |       at runMicrotasks (<anonymous>)
hardhat    |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hardhat    |       at runNextTicks (node:internal/process/task_queues:65:3)
hardhat    |       at listOnTimeout (node:internal/timers:528:9)
hardhat    |       at processTimers (node:internal/timers:502:7)
hardhat    | 
hardhat    |   12) AladdinZap.spec
hardhat    |        curve aleth pool [CurveETHPool Factory]
hardhat    |          should succeed, when RemoveLiquidity Curve alETH Pool => alETH:
hardhat    |      Error: Timeout of 400000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/usr/app/test/zap/AladdinZap.spec.ts)
hardhat    |       at runMicrotasks (<anonymous>)
hardhat    |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hardhat    |       at runNextTicks (node:internal/process/task_queues:65:3)
hardhat    |       at listOnTimeout (node:internal/timers:528:9)
hardhat    |       at processTimers (node:internal/timers:502:7)
hardhat    | 
hardhat    |   13) AladdinZap.spec
hardhat    |        curve cvxeth pool [CurveCryptoPool]
hardhat    |          should succeed, when RemoveLiquidity Curve cvxeth Pool => ETH:
hardhat    |      Error: Timeout of 400000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/usr/app/test/zap/AladdinZap.spec.ts)
hardhat    |       at runMicrotasks (<anonymous>)
hardhat    |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hardhat    |       at runNextTicks (node:internal/process/task_queues:65:3)
hardhat    |       at listOnTimeout (node:internal/timers:528:9)
hardhat    |       at processTimers (node:internal/timers:502:7)
hardhat    | 
hardhat    |   14) TokenZapLogic.spec
hardhat    |        Curve Factory_LUSD, type[CurveFactoryMetaPool], tokens[2]
hardhat    |          "before each" hook for "should succeed, when remove liquidity to LUSD":
hardhat    |      InvalidInputError: unknown account 0xda9dfa130df4de4673b89022ee50ff26f6ea73cf
hardhat    |       at HardhatNode.getSignedTransaction (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:433:11)
hardhat    |       at EthModule._sendTransactionAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1036:33)
hardhat    |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
hardhat    |       at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
hardhat    |       at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)